/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopostgres;
import java.sql.*; //Clases de conexión a la BD
import javax.swing.JOptionPane; //Clase para manejo de formas
import javax.swing.table.DefaultTableModel; //Clase para el manejo de JTable
import java.util.ArrayList;
/**
 *
 * @author rafael
 */
public class FormSeekClient extends javax.swing.JFrame {

    /**
     * Creates new form FormSeekClient
     */
    private FormAddSale parent;
    private Connection connection = null; //Objeto de conexión
    private String usuario; //Usuario con el que se conecta a la BD
    private String contra;
    
    public FormSeekClient(FormAddSale par) {
        initComponents();
        parent = par;
        usuario = "superuser";
        contra = "root";
        
        openConnection(usuario,contra); //Intenta conectarse a la BD
        if(connection != null)
        {
            cargaJTable(""); //Cargar información en pantalla
            closeConnection(); //Cierra la conexión
        }
    }
    
    public void openConnection(String u, String ps)
    {
        if (connection != null)
            return;
        
        String url = "jdbc:postgresql://localhost:5432/Autos";
        try
        {
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection(url, u, ps);
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    public void closeConnection()
    {
        try
        {
            if(connection!=null)
            {
                connection.close();
                connection = null;      
            }
        }catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    
    private void cargaJTable(String search)
    {
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsm;
        DefaultTableModel dtm;
        String query = "";
        try{
            if(search.equals(""))
                query = "SELECT * FROM \"cliente\"";
            else
                query = "SELECT * FROM \"cliente\" WHERE nombre LIKE '" + search + "%'";
            ps = connection.prepareStatement(query);
            rs = ps.executeQuery();
            rsm = rs.getMetaData();
            ArrayList<Object[]> data = new ArrayList<>();
           
            while(rs.next())
            {
                Object[] rows = new Object[rsm.getColumnCount()];
                for(int i = 0; i < rows.length; i ++)
                {
                    rows[i] = rs.getObject(i+1);
                }
                data.add(rows);
            }
           
            dtm = (DefaultTableModel)this.jTable1.getModel();
            dtm.setRowCount(0);
            for(int i = 0; i < data.size(); i ++)
            {
                dtm.addRow(data.get(i));
            }
            rs.close();
            ps.close();
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbName = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        bSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(426, 338));
        setSize(new java.awt.Dimension(426, 338));

        jScrollPane1.setViewportView(tbName);

        jLabel1.setText("Nombre:");

        bSearch.setText("Buscar");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Direccion", "Telefono", "Ocupacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSearch)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        parent.setIdCliente(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        parent.setNombreCliente(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        parent.setDomicilio(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        parent.setTelefono(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        openConnection(usuario,contra);
        if(connection != null)
        {
            cargaJTable(tbName.getText());
            closeConnection();
        }
    }//GEN-LAST:event_bSearchActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane tbName;
    // End of variables declaration//GEN-END:variables
}
